[build]
  command = "pip install -r requirements.txt"
  functions = "."
  
[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200

[functions]
  directory = "."
  node_bundler = "none"
